#!/usr/bin/env bash
# redirecting to 301

sudo apt-get -y update
sudo apt-get -y install nginx
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name troy-yey.tech;
        location /redirect_me {
                return 301 https://youtu.be/mtSmAqwiuKY?list=RDmtSmAqwiuKY;
        }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
