#!/usr/bin/env bash
# script for installing and configuring loadbalancer haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "

frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 523707-web-01 54.209.125.126:80 check
    server 523707-web-02 54.85.96.138:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
