#!/usr/bin/env bash
# fizzbuz shcool.

number=1
while [ $number -ne "101" ]
do
	if [ $((number%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((number%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((number%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$number"
	fi
	(( number++ ))
done
