#!/usr/bin/env bash
# print on terminal hello school ten times

i=0
while [ $i -ne "20" ]; do
	((i++))
	echo "$i"
	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
		esac
done
