#!/usr/bin/env bash
# print minutes on hours

hour=0
while [ $hour -ne "13" ]; do
	echo "Hour: $hour"
	(( hour++ ))
	minute=1
	while [ $minute -ne "60" ]; do
		echo "$minute"
		(( minute++ ))
	done
done
