#!/usr/bin/env bash
#installing ufw and configure it so it will deny all trafic but the specified ones

sudo apt update
sudo apt install -y ufw
sudo ufw disable
sudo systemctl stop ufw
echo "y" | sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo systemctl start ufw
echo "y" | sudo ufw enable
