#!/usr/bin/env bash
#change localhost ip and add new destination for facebook

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1\(.*localhost\)/127.0.0.2\1/" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
